name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: chetan-codes
          outputs: |
            output/github-contribution-grid-snake-dark.svg?theme=dark
      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: output/
